services:
  web:
    container_name: yahtzee-game-web
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./:/app
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0 --port 5173"
    ports:
      - "5173:5173"
    networks:
      - dev-network

networks:
  dev-network:
    external: true
